apiVersion: v1
kind: Pod
metadata:
  name: hass-io-pd
  labels:
    run: hass-io-pd
spec:
  containers:
  - image: homeassistant/home-assistant:stable
    name: hass-io-container
    env:
    - name: TZ
      value: "Europe/Berlin"
    ports:
    - containerPort: 8123
      protocol: TCP
    #- containerPort: 5353
    #  protocol: UDP
    volumeMounts:
    - mountPath: /config
      name: hass-io-config
    #- mountPath: /dev/ttyACM0
    #  name: ttyacm1
  volumes:
  - name: hass-io-config
    hostPath:
      path: %BASEDIR%/hass.io
      type: DirectoryOrCreate
  #- name: ttyacm1
  #  hostPath:
  #    path: /dev/ttyACM1
  #    type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: hass-io-pd
spec:
  type: NodePort
  ports:
  - port: 8123
    name: 8123tcp
    targetPort: 8123
    protocol: TCP
    nodePort: 8123
  #- port: 5353
  #  name: 5353udp
  #  targetPort: 5353
  #  protocol: UDP
  #  nodePort: 5353
  selector:
    run: hass-io-pd
